### ISSUE TITLE
When Connecting with a Client such as MQTTLens, Broker Module throws Invalid client Index 0, but no other clients can connect

### ISSUE THREAD

**Issue by maglite4cell** [sahajquinci/simplwmqttbroker#1]
Trying various configurations, I ran into an issue where I can not use a MQTT client such as MQTTLens to view telemetry.  When Connecting, the module throws an error: ClientConnected: Invalid client Index 0.

After this error, no other users can connect.

Processor: AV3
Firmware; 1.603.4298.28152
Using: NO TLS module

SIMPL Windows:  4.14.21
SIMPL+  4.05.01
Path:  C:\Program Files (x86)\Crestron\Simpl

INCLUDE4_2SERIES.DAT Version Information:
        (2 Series)  : 1.80

INCLUDE4.DAT Version Information:
        (3 & 4 Series)  : 2.14.131

Data Files:
        Path: C:\Program Files (x86)\Crestron\Cresdb\Programming

Symlib2.Tio 1125  11/30/2020 06:11:24PM 

  iodev.tio 1125  11/30/2020 06:11:22PM 

Other Crestron SW:

        Device Database: 200.35.003.00
        Crestron Database (cnctrldb22000.mdb) :  202.00.001.00
        Crestron Toolbox: 3.07.323.00
        SIMPL+ Cross Compiler: 1.3

Client ID: lens
HEX DUMP from Wireshark
```
00000000  10 12 00 06 4d 51 49 73  64 70 03 02 00 78 00 04   ....MQIs dp...x..
00000010  6c 65 6e 73                                                               lens
```

**Comment by sahajquinci** [comment]
The broker doesn't support reconnection, therefore any connection must start with clean session true.

What's your MQTTLens configuration ?

**Comment by maglite4cell** [comment]
I have no issue connecting with a ESP8266.  As soon as I try to connect with MQTTLens, and power cycle the ESP8266, it can no longer reconnect.  If a power cycle is done without trying to connect MQTTLens, there is no issue.

![image](https://user-images.githubusercontent.com/5313447/104363490-3fd27a80-54e3-11eb-828f-ad3fbc25e52b.png)

**Comment by sahajquinci** [comment]
Have you enabled Log on your control system ? if so you should be seeing a stack trace in the Toolbox's console.

DebugLevel = "0" For logging everything 
DebugLevel = "8" For exceptions only

**Comment by maglite4cell** [comment]
That is the other weird thing, is that the Logger is not initialized in the processor I am running, and I tried to track that down.  I am running in slot 4.  I will try to get debug messages back.

**Comment by maglite4cell** [comment]
I found out a few items when working through some of this.

1) When loading to a processor without any other code, it seems to run fine, but have not tested MQTTLens with it.  I am running the NO TLS demo.
2) When running that demo, on another processor in slot 4, it gives me an error: Logger: Please initialize the Logger before attempting to print the log
3) I attempted to do some testing, but it looks like the code you have in the repo, does not have one that is non-tls.  So when I made some changes for testing, I was not able to accurately make the changes, without changing all of the SecureTCP clients to standard Crestron TCP as you had done.

Do you have the code that has the non TLS?  This might be some of my issues, and would like to give you some more debug issues.

**Comment by sahajquinci** [comment]
3 - The reason why there's a TLS and a non TLS version is that Crestron's TCP server class and SecureTCPServer class do not have 
      a common base class, but you can safely do a replace all of SecureTCPServer  with TCPServer and everything works fine.

2 - I find that odd, maybe you need to enable debug from toolbox ? (very random guess)
     The module initializes the logger when the Instance is created.
```
 public MqttBrokerStart()
        {
            CrestronLogger.Mode = LoggerModeEnum.DEFAULT;
            CrestronLogger.PrintTheLog(true);
            CrestronLogger.Initialize(10);
            CrestronLogger.LogOnlyCurrentDebugLevel = false;
        }
```

1 - Never had a problem with 3-series processors and multiple slots occupied. Sorry can't give you any insight with that.

**Comment by maglite4cell** [comment]
I believe this issue has to do when connecting from a different VLAN or routed network address.

**Comment by maglite4cell** [comment]
I have tested, and recompiled, and using the ENUM EthernetAdapterType.EthernetUnknownAdapter, fixes the issue where routed IPs can not connect.  This may be something to update in the source code.  I did replace all the SecureTCPServer instances with Crestron.SimplSharp.CrestronSockets.TCPServer instances, and this seems to resolve this issue.

**Comment by sahajquinci** [comment]
Great ! I don't have a Control System or the tools to test this, but you could open a PR if willing to.

**Comment by sahajquinci** [comment]
The issue has been partially solved by @gschellhas .

Regarding the invalid client index error the problem is common to the issue [https://github.com/sahajquinci/simplwmqttbroker/issues/2](url)
