### ISSUE TITLE
Broker + Client

### ISSUE THREAD

**Issue by OZEO-DOOZ** [sahajquinci/simplwmqttbroker#7]
Hi, 

Is it possible a have the broker + a client on the same processor? 

In fact, have the broker on the Crestron and use those information on the processor.

**Comment by sahajquinci** [comment]
If I understand your question correctly, you want to have both broker and client running on the same Control System.
The answer is yes, just put them in two different programs, so if program01 is your main program with the client you should put the broker in program02
